{
   "apiVersion": "cert-manager.io/v1",
   "kind": "Certificate",
   "metadata": {
      "name": "radius"
   },
   "spec": {
      "dnsNames": [
         "radius.rubykaigi.net"
      ],
      "issuerRef": {
         "kind": "ClusterIssuer",
         "name": "letsencrypt"
      },
      "secretName": "cert-radius"
   }
}
