{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "labels": {
         "rubykaigi.org/app": "radius"
      },
      "name": "radius",
      "namespace": "default"
   },
   "spec": {
      "replicas": 3,
      "selector": {
         "matchLabels": {
            "rubykaigi.org/app": "radius"
         }
      },
      "template": {
         "metadata": {
            "labels": {
               "rubykaigi.org/app": "radius"
            }
         },
         "spec": {
            "containers": [
               {
                  "command": [
                     "/run.sh"
                  ],
                  "env": [
                     {
                        "name": "RADIUS_SECRET",
                        "valueFrom": {
                           "secretKeyRef": {
                              "key": "secret",
                              "name": "radius"
                           }
                        }
                     }
                  ],
                  "image": "005216166247.dkr.ecr.ap-northeast-1.amazonaws.com/radiusd:bf1b115eff0ec17dbc071416075fe99de4538d9b",
                  "name": "app",
                  "ports": [
                     {
                        "containerPort": 1812,
                        "name": "radius",
                        "protocol": "UDP"
                     },
                     {
                        "containerPort": 1812,
                        "name": "radius-tcp",
                        "protocol": "TCP"
                     }
                  ],
                  "resources": {
                     "requests": {
                        "cpu": "5m",
                        "memory": "96M"
                     }
                  },
                  "volumeMounts": [
                     {
                        "mountPath": "/secrets/tls-cert",
                        "name": "tls-cert"
                     }
                  ]
               },
               {
                  "command": [
                     "/usr/local/bin/freeradius_exporter"
                  ],
                  "env": [
                     {
                        "name": "RADIUS_SECRET",
                        "value": "maplenutbunny"
                     }
                  ],
                  "image": "005216166247.dkr.ecr.ap-northeast-1.amazonaws.com/freeradius-exporter:bf1b115eff0ec17dbc071416075fe99de4538d9b",
                  "livenessProbe": {
                     "failureThreshold": 2,
                     "httpGet": {
                        "path": "/metrics",
                        "port": 9812,
                        "scheme": "HTTP"
                     },
                     "periodSeconds": 45
                  },
                  "name": "exporter",
                  "ports": [
                     {
                        "containerPort": 9812,
                        "name": "prom",
                        "protocol": "TCP"
                     }
                  ],
                  "readinessProbe": {
                     "httpGet": {
                        "path": "/metrics",
                        "port": 9812,
                        "scheme": "HTTP"
                     }
                  },
                  "resources": {
                     "requests": {
                        "cpu": "5m",
                        "memory": "10M"
                     }
                  }
               }
            ],
            "topologySpreadConstraints": [
               {
                  "labelSelector": {
                     "matchLabels": {
                        "rubykaigi.org/app": "radius"
                     }
                  },
                  "matchLabelKeys": [
                     "pod-template-hash"
                  ],
                  "maxSkew": 1,
                  "topologyKey": "topology.kubernetes.io/zone",
                  "whenUnsatisfiable": "DoNotSchedule"
               }
            ],
            "volumes": [
               {
                  "name": "tls-cert",
                  "secret": {
                     "secretName": "cert-radius"
                  }
               }
            ]
         }
      }
   }
}
