<%-
  addrs4 = node.dig(:acme_responder, :overlay, :address4)
  addrs6 = node.dig(:acme_responder, :overlay, :address6)
-%>
# vim: set ft=bird nofoldenable:

define C_SELF = 4264600034;

ipv4 table bgp4;
ipv6 table bgp6;

protocol direct {
  ipv4 {
    table bgp4;
  };
  ipv6 {
    table bgp6;
  };
  interface "lo";
}

protocol kernel kernel_overlay4 {
  persist;
  kernel table 80;
  ipv4 {
    table bgp4;
    import none;
    export where source = RTS_BGP;
  };
}

protocol kernel kernel_overlay6 {
  persist;
  kernel table 80;
  ipv6 {
    table bgp6;
    import none;
    export where source = RTS_BGP;
  };
}

protocol bgp bgp_rola {
  interface "ip6tnl-rola";
  local fe80::b as C_SELF;
  neighbor fe80::a as 59128;

  hold time 30;
  startup hold time 90;
  keepalive time 6;
  connect retry time 5;
  start delay time 5;
  error wait time 30, 30;
  error forget time 30;

  default bgp_local_pref 90;

  ipv4 {
    table bgp4;
    extended next hop on;
    import filter {
      if net = 0.0.0.0/0 then accept;
      reject;
    };
    export filter {
      if net ~ [ <%= addrs4.map { |a| "#{a}+" }.join(', ') %> ] then { bgp_path.prepend(C_SELF); accept; }
      reject;
    };
  };

  ipv6 {
    table bgp6;
    import filter {
      if net = ::/0 then accept;
      reject;
    };
    export filter {
      if net ~ [ <%= addrs6.map { |a| "#{a}+" }.join(', ') %> ] then { bgp_path.prepend(C_SELF); accept; }
      reject;
    };
  };
}

protocol bgp bgp_mahiru {
  interface "ip6tnl-mahiru";
  local fe80::b as C_SELF;
  neighbor fe80::a as 59128;

  hold time 30;
  startup hold time 90;
  keepalive time 6;
  connect retry time 5;
  start delay time 5;
  error wait time 30, 30;
  error forget time 30;

  default bgp_local_pref 100;

  ipv4 {
    table bgp4;
    extended next hop on;
    import filter {
      if net = 0.0.0.0/0 then accept;
      reject;
    };
    export filter {
      if net ~ [ <%= addrs4.map { |a| "#{a}+" }.join(', ') %> ] then accept;
      reject;
    };
  };

  ipv6 {
    table bgp6;
    import filter {
      if net = ::/0 then accept;
      reject;
    };
    export filter {
      if net ~ [ <%= addrs6.map { |a| "#{a}+" }.join(', ') %> ] then accept;
      reject;
    };
  };
}
