{
   "apiVersion": "monitoring.coreos.com/v1alpha1",
   "kind": "ScrapeConfig",
   "metadata": {
      "labels": {
         "release": "kube-prometheus-stack"
      },
      "name": "cloudprober"
   },
   "spec": {
      "dnsSDConfigs": [
         {
            "names": [
               "_prometheus._http.cloudprober.rubykaigi.net"
            ]
         }
      ]
   }
}
