{
  "apiVersion": "monitoring.coreos.com/v1",
  "kind": "Probe",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-hi-if-mib"
  },
  "spec": {
    "interval": "20s",
    "module": "if_mib",
    "prober": {
      "path": "/snmp",
      "url": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116"
    },
    "scrapeTimeout": "19s",
    "targets": {
      "staticConfig": {
        "static": [
          "br-01.hnd.rubykaigi.net",
          "br-01.nrt.rubykaigi.net",
          "tun-01.venue.rubykaigi.net",
          "tun-02.venue.rubykaigi.net",
          "gw-01.venue.rubykaigi.net",
          "gw-02.venue.rubykaigi.net",
          "tun-01.hot.rubykaigi.net",
          "gw-01.hot.rubykaigi.net",
          "tun-99.tkyk.rubykaigi.net",
          "gw-99.tkyk.rubykaigi.net",
          "esw-tra-01.venue.rubykaigi.net",
          "esw-tra-02.venue.rubykaigi.net",
          "esw-fow-01.venue.rubykaigi.net",
          "esw-foe-01.venue.rubykaigi.net",
          "esw-trb-01.venue.rubykaigi.net",
          "esw-tpk-01.venue.rubykaigi.net",
          "esw-tpk-02.venue.rubykaigi.net",
          "esw-trc-01.venue.rubykaigi.net",
          "esw-stu-01.venue.rubykaigi.net",
          "esw-con-01.venue.rubykaigi.net",
          "esw-org-01.venue.rubykaigi.net"
        ]
      }
    }
  }
}
---
{
  "apiVersion": "monitoring.coreos.com/v1",
  "kind": "Probe",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-hi-nec-ix"
  },
  "spec": {
    "interval": "20s",
    "module": "nec_ix",
    "prober": {
      "path": "/snmp",
      "url": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116"
    },
    "scrapeTimeout": "19s",
    "targets": {
      "staticConfig": {
        "static": [
          "br-01.hnd.rubykaigi.net",
          "br-01.nrt.rubykaigi.net",
          "tun-01.venue.rubykaigi.net",
          "tun-02.venue.rubykaigi.net",
          "gw-01.venue.rubykaigi.net",
          "gw-02.venue.rubykaigi.net",
          "tun-01.hot.rubykaigi.net",
          "gw-01.hot.rubykaigi.net",
          "tun-99.tkyk.rubykaigi.net",
          "gw-99.tkyk.rubykaigi.net"
        ]
      }
    }
  }
}
---
{
  "apiVersion": "monitoring.coreos.com/v1",
  "kind": "Probe",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-lo-cisco-envmon"
  },
  "spec": {
    "interval": "60s",
    "module": "cisco_envmon",
    "prober": {
      "path": "/snmp",
      "url": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116"
    },
    "scrapeTimeout": "59s",
    "targets": {
      "staticConfig": {
        "static": [
          "esw-tra-01.venue.rubykaigi.net",
          "esw-tra-02.venue.rubykaigi.net",
          "esw-fow-01.venue.rubykaigi.net",
          "esw-foe-01.venue.rubykaigi.net",
          "esw-trb-01.venue.rubykaigi.net",
          "esw-tpk-01.venue.rubykaigi.net",
          "esw-tpk-02.venue.rubykaigi.net",
          "esw-trc-01.venue.rubykaigi.net",
          "esw-stu-01.venue.rubykaigi.net",
          "esw-con-01.venue.rubykaigi.net",
          "esw-org-01.venue.rubykaigi.net"
        ]
      }
    }
  }
}
---
{
  "apiVersion": "monitoring.coreos.com/v1",
  "kind": "Probe",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-lo-cisco-sensors"
  },
  "spec": {
    "interval": "60s",
    "module": "cisco_sensors",
    "prober": {
      "path": "/snmp",
      "url": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116"
    },
    "scrapeTimeout": "59s",
    "targets": {
      "staticConfig": {
        "static": [
          "esw-tra-01.venue.rubykaigi.net",
          "esw-tra-02.venue.rubykaigi.net",
          "esw-fow-01.venue.rubykaigi.net",
          "esw-foe-01.venue.rubykaigi.net",
          "esw-trb-01.venue.rubykaigi.net",
          "esw-tpk-01.venue.rubykaigi.net",
          "esw-tpk-02.venue.rubykaigi.net",
          "esw-trc-01.venue.rubykaigi.net",
          "esw-stu-01.venue.rubykaigi.net",
          "esw-con-01.venue.rubykaigi.net",
          "esw-org-01.venue.rubykaigi.net"
        ]
      }
    }
  }
}
---
{
  "apiVersion": "monitoring.coreos.com/v1",
  "kind": "Probe",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-lo-cisco-wlc"
  },
  "spec": {
    "interval": "60s",
    "module": "cisco_wlc",
    "prober": {
      "path": "/snmp",
      "url": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116"
    },
    "scrapeTimeout": "59s",
    "targets": {
      "staticConfig": {
        "static": [
          "wlc-01.venue.rubykaigi.net"
        ]
      }
    }
  }
}
---
{
  "apiVersion": "monitoring.coreos.com/v1",
  "kind": "Probe",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-lo-if-mib"
  },
  "spec": {
    "interval": "60s",
    "module": "if_mib",
    "prober": {
      "path": "/snmp",
      "url": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116"
    },
    "scrapeTimeout": "59s",
    "targets": {
      "staticConfig": {
        "static": [
          "csw-01.venue.rubykaigi.net"
        ]
      }
    }
  }
}
---
{
  "apiVersion": "monitoring.coreos.com/v1",
  "kind": "Probe",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-lo-if-mib2"
  },
  "spec": {
    "interval": "60s",
    "module": "if_mib2",
    "prober": {
      "path": "/snmp",
      "url": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116"
    },
    "scrapeTimeout": "59s",
    "targets": {
      "staticConfig": {
        "static": [
          "wlc-01.venue.rubykaigi.net"
        ]
      }
    }
  }
}
---
