{
  "apiVersion": "monitoring.coreos.com/v1alpha1",
  "kind": "ScrapeConfig",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-hi-cisco-esw"
  },
  "spec": {
    "metricsPath": "/snmp",
    "params": {
      "auth": [
        "public"
      ],
      "module": [
        "if_mib"
      ]
    },
    "relabelings": [
      {
        "sourceLabels": [
          "__address__"
        ],
        "targetLabel": "__param_target"
      },
      {
        "sourceLabels": [
          "__param_target"
        ],
        "targetLabel": "instance"
      },
      {
        "replacement": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116",
        "targetLabel": "__address__"
      }
    ],
    "scrapeInterval": "20s",
    "scrapeTimeout": "19s",
    "staticConfigs": [
      {
        "targets": [
          "cs-99.tkyk.rubykaigi.net"
        ]
      }
    ]
  }
}
---
{
  "apiVersion": "monitoring.coreos.com/v1alpha1",
  "kind": "ScrapeConfig",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-hi-ix"
  },
  "spec": {
    "metricsPath": "/snmp",
    "params": {
      "auth": [
        "public"
      ],
      "module": [
        "if_mib",
        "nec_ix"
      ]
    },
    "relabelings": [
      {
        "sourceLabels": [
          "__address__"
        ],
        "targetLabel": "__param_target"
      },
      {
        "sourceLabels": [
          "__param_target"
        ],
        "targetLabel": "instance"
      },
      {
        "replacement": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116",
        "targetLabel": "__address__"
      }
    ],
    "scrapeInterval": "20s",
    "scrapeTimeout": "19s",
    "staticConfigs": [
      {
        "targets": [
          "tun-01.hnd.rubykaigi.net",
          "tun-01.nrt.rubykaigi.net",
          "tun-01.itm.rubykaigi.net",
          "tun-01.venue.rubykaigi.net",
          "tun-02.venue.rubykaigi.net",
          "nat-41.venue.rubykaigi.net",
          "nat-42.venue.rubykaigi.net",
          "tun-99.tkyk.rubykaigi.net",
          "nat-49.tkyk.rubykaigi.net"
        ]
      }
    ]
  }
}
---
{
  "apiVersion": "monitoring.coreos.com/v1alpha1",
  "kind": "ScrapeConfig",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-lo-cisco-esw"
  },
  "spec": {
    "metricsPath": "/snmp",
    "params": {
      "auth": [
        "public"
      ],
      "module": [
        "cisco_envmon",
        "cisco_sensors"
      ]
    },
    "relabelings": [
      {
        "sourceLabels": [
          "__address__"
        ],
        "targetLabel": "__param_target"
      },
      {
        "sourceLabels": [
          "__param_target"
        ],
        "targetLabel": "instance"
      },
      {
        "replacement": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116",
        "targetLabel": "__address__"
      }
    ],
    "scrapeInterval": "60s",
    "scrapeTimeout": "59s",
    "staticConfigs": [
      {
        "targets": [
          "cs-99.tkyk.rubykaigi.net"
        ]
      }
    ]
  }
}
---
{
  "apiVersion": "monitoring.coreos.com/v1alpha1",
  "kind": "ScrapeConfig",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-lo-cisco-wlc"
  },
  "spec": {
    "metricsPath": "/snmp",
    "params": {
      "auth": [
        "public2"
      ],
      "module": [
        "if_mib",
        "cisco_wlc"
      ]
    },
    "relabelings": [
      {
        "sourceLabels": [
          "__address__"
        ],
        "targetLabel": "__param_target"
      },
      {
        "sourceLabels": [
          "__param_target"
        ],
        "targetLabel": "instance"
      },
      {
        "replacement": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116",
        "targetLabel": "__address__"
      }
    ],
    "scrapeInterval": "60s",
    "scrapeTimeout": "59s",
    "staticConfigs": [
      {
        "targets": [

        ]
      }
    ]
  }
}
---
{
  "apiVersion": "monitoring.coreos.com/v1alpha1",
  "kind": "ScrapeConfig",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-lo-cisco-wlc-tkyk"
  },
  "spec": {
    "metricsPath": "/snmp",
    "params": {
      "auth": [
        "tkyk"
      ],
      "module": [
        "if_mib",
        "cisco_wlc"
      ]
    },
    "relabelings": [
      {
        "sourceLabels": [
          "__address__"
        ],
        "targetLabel": "__param_target"
      },
      {
        "sourceLabels": [
          "__param_target"
        ],
        "targetLabel": "instance"
      },
      {
        "replacement": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116",
        "targetLabel": "__address__"
      }
    ],
    "scrapeInterval": "60s",
    "scrapeTimeout": "59s",
    "staticConfigs": [
      {
        "targets": [
          "wlc-99.tkyk.rubykaigi.net"
        ]
      }
    ]
  }
}
---
{
  "apiVersion": "monitoring.coreos.com/v1alpha1",
  "kind": "ScrapeConfig",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-lo-juniper-ex"
  },
  "spec": {
    "metricsPath": "/snmp",
    "params": {
      "auth": [
        "public"
      ],
      "module": [
        "if_mib_juniper1",
        "if_mib_juniper2",
        "juniper_alarm",
        "juniper_chassis",
        "juniper_dom",
        "juniper_bgp",
        "juniper_virtualchassis"
      ]
    },
    "relabelings": [
      {
        "sourceLabels": [
          "__address__"
        ],
        "targetLabel": "__param_target"
      },
      {
        "sourceLabels": [
          "__param_target"
        ],
        "targetLabel": "instance"
      },
      {
        "replacement": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116",
        "targetLabel": "__address__"
      }
    ],
    "scrapeInterval": "60s",
    "scrapeTimeout": "59s",
    "staticConfigs": [
      {
        "targets": [
          "cs-01.venue.rubykaigi.net"
        ]
      }
    ]
  }
}
---
{
  "apiVersion": "monitoring.coreos.com/v1alpha1",
  "kind": "ScrapeConfig",
  "metadata": {
    "labels": {
      "release": "kube-prometheus-stack"
    },
    "name": "snmp-lo-juniper-srx"
  },
  "spec": {
    "metricsPath": "/snmp",
    "params": {
      "auth": [
        "public"
      ],
      "module": [
        "if_mib_juniper1",
        "if_mib_juniper2",
        "juniper_alarm",
        "juniper_chassis",
        "juniper_bgp"
      ]
    },
    "relabelings": [
      {
        "sourceLabels": [
          "__address__"
        ],
        "targetLabel": "__param_target"
      },
      {
        "sourceLabels": [
          "__param_target"
        ],
        "targetLabel": "instance"
      },
      {
        "replacement": "snmp-exporter-prometheus-snmp-exporter.default.svc.cluster.local:9116",
        "targetLabel": "__address__"
      }
    ],
    "scrapeInterval": "60s",
    "scrapeTimeout": "59s",
    "staticConfigs": [
      {
        "targets": [
          "br-01.hnd.rubykaigi.net",
          "br-01.nrt.rubykaigi.net",
          "br-01.itm.rubykaigi.net",
          "er-01.venue.rubykaigi.net",
          "er-02.venue.rubykaigi.net",
          "er-99.tkyk.rubykaigi.net"
        ]
      }
    ]
  }
}
---
