{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "unbound"
  },
  "spec": {
    "ports": [
      {
        "name": "dns",
        "port": 53,
        "protocol": "UDP",
        "targetPort": "dns"
      },
      {
        "name": "dns-tcp",
        "port": 53,
        "protocol": "TCP",
        "targetPort": "dns-tcp"
      }
    ],
    "selector": {
      "rubykaigi.org/app": "unbound"
    }
  }
}
---
