{
   "apiVersion": "karpenter.k8s.aws/v1",
   "kind": "EC2NodeClass",
   "metadata": {
      "name": "general"
   },
   "spec": {
      "amiFamily": "Bottlerocket",
      "amiSelectorTerms": [
         {
            "alias": "bottlerocket@latest"
         }
      ],
      "instanceProfile": "NetEksKarpenterNode-rknet",
      "kubelet": {
         "kubeReserved": {
            "cpu": "70m",
            "ephemeral-storage": "1Gi",
            "memory": "300Mi"
         },
         "maxPods": 110
      },
      "securityGroupSelectorTerms": [
         {
            "tags": {
               "aws:eks:cluster-name": "rknet",
               "kubernetes.io/cluster/rknet": "owned"
            }
         }
      ],
      "subnetSelectorTerms": [
         {
            "tags": {
               "Tier": "private",
               "kubernetes.io/cluster/rknet": "shared"
            }
         }
      ],
      "tags": {
         "Component": "k8s",
         "KarpenterNodeClass": "general",
         "Project": "rk25net",
         "Role": "kubelet/general"
      },
      "userData": "[settings.container-registry.mirrors]\n\"docker.io\" = [\"https://mirror.gcr.io\"]\n"
   }
}
