{
   "apiVersion": "karpenter.k8s.aws/v1beta1",
   "kind": "EC2NodeClass",
   "metadata": {
      "name": "onpremises"
   },
   "spec": {
      "amiFamily": "Bottlerocket",
      "instanceProfile": "NetEksKarpenterNode-rknet",
      "securityGroupSelectorTerms": [
         {
            "tags": {
               "aws:eks:cluster-name": "rknet",
               "kubernetes.io/cluster/rknet": "owned"
            }
         }
      ],
      "subnetSelectorTerms": [
         {
            "tags": {
               "Tier": "onpremises",
               "kubernetes.io/cluster/rknet": "shared"
            }
         }
      ],
      "tags": {
         "Component": "k8s",
         "KarpenterNodeClass": "onpremises",
         "Project": "rk24net",
         "Role": "kubelet"
      }
   }
}
