{
   "apiVersion": "karpenter.sh/v1",
   "kind": "NodePool",
   "metadata": {
      "name": "onpremises"
   },
   "spec": {
      "disruption": {
         "budgets": [
            {
               "nodes": "30%"
            }
         ],
         "consolidateAfter": "1m",
         "consolidationPolicy": "WhenEmptyOrUnderutilized"
      },
      "template": {
         "metadata": {
            "labels": {
               "rubykaigi.org/node-group": "onpremises"
            }
         },
         "spec": {
            "expireAfter": "24h",
            "nodeClassRef": {
               "group": "karpenter.k8s.aws",
               "kind": "EC2NodeClass",
               "name": "onpremises"
            },
            "requirements": [
               {
                  "key": "karpenter.k8s.aws/instance-category",
                  "operator": "In",
                  "values": [
                     "t"
                  ]
               },
               {
                  "key": "kubernetes.io/arch",
                  "operator": "In",
                  "values": [
                     "arm64"
                  ]
               },
               {
                  "key": "kubernetes.io/os",
                  "operator": "In",
                  "values": [
                     "linux"
                  ]
               },
               {
                  "key": "karpenter.sh/capacity-type",
                  "operator": "In",
                  "values": [
                     "spot",
                     "on-demand"
                  ]
               },
               {
                  "key": "node.kubernetes.io/instance-type",
                  "operator": "NotIn",
                  "values": [
                     "t4g.nano",
                     "t4g.micro"
                  ]
               }
            ],
            "taints": [
               {
                  "effect": "NoSchedule",
                  "key": "dedicated",
                  "value": "onpremises"
               }
            ]
         }
      },
      "weight": 5
   }
}
