# vim: set ft=bird nofoldenable:
<%-
  downstream = node.dig(:wire, :interfaces, :downstream)
  tunnels    = node.fetch(:wire).fetch(:tunnels, {})
  loopback6  = [*node.dig(:wire, :interfaces, :loopback).fetch(:address6)].first
  kernel_table = node.dig(:wire, :kernel_route_table)
  direct_ifaces = ['"-me0"']
  direct_ifaces << %("#{downstream.fetch(:name)}") if downstream
  direct_ifaces << '"wg_*"'
  direct_ifaces << '"lo"'
-%>

protocol direct {
  ipv4;
  ipv6;
  interface <%= direct_ifaces.join(', ') %>;
}

protocol kernel kernel4 {
  persist;
  merge paths yes;
<%- if kernel_table -%>
  kernel table <%= kernel_table %>;
<%- end -%>
  ipv4 {
    export all;
  };
}

protocol kernel kernel6 {
  persist;
  merge paths yes;
<%- if kernel_table -%>
  kernel table <%= kernel_table %>;
<%- end -%>
  ipv6 {
    export filter {
      /* Scope=link does not work for IPv6 interface address! */
      <% if loopback6 %>krt_prefsrc = <%= loopback6 %>;<% end %>
      accept;
    };
  };
}

<%- if downstream && downstream[:local_as] && downstream[:peer_as] -%>
# downstream (eBGP)
protocol bgp bgp_downstream {
  local as <%= downstream.fetch(:local_as) %>;
  neighbor <%= downstream.fetch(:link6).fetch(:peer) %> as <%= downstream.fetch(:peer_as) %>;
  hold time 24;
  keepalive time 6;

  ipv4 {
    import all;
    export all;
  };
  ipv6 {
    import all;
    export all;
  };
}
<%- end -%>

<%- tunnels.each do |name, attr| -%>
<%- next unless attr[:local_as] && attr[:peer_as] -%>
# tunnel (iBGP): <%= name %>
protocol bgp bgp_<%= name %> {
  local as <%= attr.fetch(:local_as) %>;
  neighbor <%= attr.fetch(:link6).fetch(:peer) %> as <%= attr.fetch(:peer_as) %>;
  direct;
  hold time 24;
  keepalive time 6;

  ipv4 {
    import all;
    export all;
    next hop self;
  };
  ipv6 {
    import all;
    export all;
    next hop self;
  };
}

<%- end -%>
