[Unit]
Wants=rk-move-overlay-wg-iface.service

[Service]
ExecStart=
ExecStart=/usr/bin/systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth -U --settings=override --machine=%i --load-credential=network.wireguard.private.default:%d/network.wireguard.private.default --load-credential=open-ddns-key:%d/open-ddns-key
LoadCredentialEncrypted=network.wireguard.private.default:/etc/wire.key
LoadCredentialEncrypted=open-ddns-key:/etc/open-ddns-key.key
