# vim: ft=nftables

table inet acme-responder {
  chain input {
    type filter hook input priority filter; policy accept;

    iif lo accept
    ct state established,related accept

    ip protocol icmp accept
    ip6 nexthdr icmpv6 accept

    iifname "ip6tnl-*" jump input-ip6tnl
  }

  chain input-ip6tnl {
    ip6 daddr fe80::/10 tcp dport bgp ct state new accept
    tcp dport http ct state new accept
    drop
  }
}
