{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "tftp-s3tftpd"
  },
  "spec": {
    "ports": [
      {
        "name": "tftp",
        "port": 69,
        "protocol": "UDP",
        "targetPort": "tftp"
      }
    ],
    "selector": {
      "rubykaigi.org/app": "tftp-s3tftpd"
    }
  }
}
---
{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "tftp-envoy"
  },
  "spec": {
    "ports": [
      {
        "name": "http",
        "port": 80,
        "protocol": "TCP",
        "targetPort": "http"
      }
    ],
    "selector": {
      "rubykaigi.org/app": "tftp-envoy"
    }
  }
}
---
