{
   "apiVersion": "batch/v1",
   "kind": "CronJob",
   "metadata": {
      "name": "kea-dhcp-upgrade",
      "namespace": "default"
   },
   "spec": {
      "jobTemplate": {
         "spec": {
            "template": {
               "spec": {
                  "containers": [
                     {
                        "command": [
                           "/app/db-upgrade.rb"
                        ],
                        "env": [
                           {
                              "name": "LEASE_DATABASE_NAME",
                              "value": "kea"
                           },
                           {
                              "name": "LEASE_DATABASE_HOST",
                              "value": "kea1.db.apne1.rubykaigi.net"
                           },
                           {
                              "name": "LEASE_DATABASE_USER",
                              "valueFrom": {
                                 "secretKeyRef": {
                                    "key": "username",
                                    "name": "kea-mysql"
                                 }
                              }
                           },
                           {
                              "name": "LEASE_DATABASE_PASSWORD",
                              "valueFrom": {
                                 "secretKeyRef": {
                                    "key": "password",
                                    "name": "kea-mysql"
                                 }
                              }
                           },
                           {
                              "name": "HOSTS_DATABASE_NAME",
                              "value": "kea"
                           },
                           {
                              "name": "HOSTS_DATABASE_HOST",
                              "value": "kea1.db.apne1.rubykaigi.net"
                           },
                           {
                              "name": "HOSTS_DATABASE_USER",
                              "valueFrom": {
                                 "secretKeyRef": {
                                    "key": "username",
                                    "name": "kea-mysql"
                                 }
                              }
                           },
                           {
                              "name": "HOSTS_DATABASE_PASSWORD",
                              "valueFrom": {
                                 "secretKeyRef": {
                                    "key": "password",
                                    "name": "kea-mysql"
                                 }
                              }
                           },
                           {
                              "name": "AWS_REGION",
                              "value": "ap-northeast-1"
                           },
                           {
                              "name": "KEA_ADMIN_DB_USER",
                              "value": "kea-admin"
                           }
                        ],
                        "image": "005216166247.dkr.ecr.ap-northeast-1.amazonaws.com/kea:51581786f11aa752c34bac1f0bedb44556a8a2ed",
                        "name": "app",
                        "resources": {
                           "requests": {
                              "cpu": "64m",
                              "memory": "20M"
                           }
                        },
                        "volumeMounts": [
                           {
                              "mountPath": "/config",
                              "name": "config"
                           },
                           {
                              "mountPath": "/server-ids",
                              "name": "server-ids"
                           }
                        ]
                     }
                  ],
                  "restartPolicy": "Never",
                  "serviceAccountName": "kea",
                  "volumes": [
                     {
                        "configMap": {
                           "items": [
                              {
                                 "key": "kea-dhcp4.json",
                                 "path": "kea-dhcp4.json"
                              }
                           ],
                           "name": "kea-config"
                        },
                        "name": "config"
                     },
                     {
                        "configMap": {
                           "items": [
                              {
                                 "key": "server-ids.json",
                                 "path": "server-ids.json"
                              }
                           ],
                           "name": "kea-server-ids"
                        },
                        "name": "server-ids"
                     }
                  ]
               }
            }
         }
      },
      "schedule": "0 * * * *",
      "suspend": true
   }
}
