{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "labels": {
         "rubykaigi.org/app": "kea4"
      },
      "name": "kea4",
      "namespace": "default"
   },
   "spec": {
      "replicas": 3,
      "selector": {
         "matchLabels": {
            "rubykaigi.org/app": "kea4"
         }
      },
      "template": {
         "metadata": {
            "labels": {
               "rubykaigi.org/app": "kea4"
            }
         },
         "spec": {
            "containers": [
               {
                  "command": [
                     "/bin/bash",
                     "-e",
                     "/app/run.sh"
                  ],
                  "env": [
                     {
                        "name": "LEASE_DATABASE_USER",
                        "valueFrom": {
                           "secretKeyRef": {
                              "key": "username",
                              "name": "kea-mysql"
                           }
                        }
                     },
                     {
                        "name": "LEASE_DATABASE_PASSWORD",
                        "valueFrom": {
                           "secretKeyRef": {
                              "key": "password",
                              "name": "kea-mysql"
                           }
                        }
                     },
                     {
                        "name": "HOSTS_DATABASE_USER",
                        "valueFrom": {
                           "secretKeyRef": {
                              "key": "username",
                              "name": "kea-mysql"
                           }
                        }
                     },
                     {
                        "name": "HOSTS_DATABASE_PASSWORD",
                        "valueFrom": {
                           "secretKeyRef": {
                              "key": "password",
                              "name": "kea-mysql"
                           }
                        }
                     }
                  ],
                  "image": "005216166247.dkr.ecr.ap-northeast-1.amazonaws.com/kea:4b1dc5bf74750690899ea5a3fda005c6179fd993",
                  "livenessProbe": {
                     "failureThreshold": 2,
                     "httpGet": {
                        "path": "/healthz",
                        "port": 10067,
                        "scheme": "HTTP"
                     },
                     "periodSeconds": 3
                  },
                  "name": "app",
                  "ports": [
                     {
                        "containerPort": 67,
                        "name": "dhcp",
                        "protocol": "UDP"
                     },
                     {
                        "containerPort": 9547,
                        "name": "prom"
                     },
                     {
                        "containerPort": 10067,
                        "name": "healthz"
                     }
                  ],
                  "readinessProbe": {
                     "httpGet": {
                        "path": "/healthz",
                        "port": 10067,
                        "scheme": "HTTP"
                     }
                  },
                  "resources": {
                     "requests": {
                        "cpu": "5m",
                        "memory": "20M"
                     }
                  },
                  "volumeMounts": [
                     {
                        "mountPath": "/config",
                        "name": "config"
                     }
                  ]
               }
            ],
            "topologySpreadConstraints": [
               {
                  "labelSelector": {
                     "matchLabels": {
                        "rubykaigi.org/app": "kea4"
                     }
                  },
                  "matchLabelKeys": [
                     "pod-template-hash"
                  ],
                  "maxSkew": 1,
                  "topologyKey": "topology.kubernetes.io/zone",
                  "whenUnsatisfiable": "DoNotSchedule"
               }
            ],
            "volumes": [
               {
                  "configMap": {
                     "items": [
                        {
                           "key": "kea-dhcp4.json",
                           "path": "kea-dhcp4.json"
                        }
                     ],
                     "name": "kea-config"
                  },
                  "name": "config"
               }
            ]
         }
      }
   }
}
