{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "kea4",
    "namespace": "default"
  },
  "spec": {
    "ports": [
      {
        "name": "dhcp",
        "port": 67,
        "protocol": "UDP",
        "targetPort": "dhcp"
      }
    ],
    "selector": {
      "rubykaigi.org/app": "kea4"
    }
  }
}
---
