{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "annotations": {
      "service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags": "Project=rk25net,Component=dhcp",
      "service.beta.kubernetes.io/aws-load-balancer-healthcheck-path": "/healthz",
      "service.beta.kubernetes.io/aws-load-balancer-healthcheck-port": "10067",
      "service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol": "HTTP",
      "service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules": "false",
      "service.beta.kubernetes.io/aws-load-balancer-nlb-target-type": "ip",
      "service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses": "10.33.136.67,10.33.152.67",
      "service.beta.kubernetes.io/aws-load-balancer-scheme": "internal",
      "service.beta.kubernetes.io/aws-load-balancer-subnets": "subnet-03b83376cdff5f681,subnet-04459368f75060d34",
      "service.beta.kubernetes.io/aws-load-balancer-target-group-attributes": "deregistration_delay.timeout_seconds=10,deregistration_delay.connection_termination.enabled=true"
    },
    "name": "kea4",
    "namespace": "default"
  },
  "spec": {
    "loadBalancerClass": "service.k8s.aws/nlb",
    "ports": [
      {
        "name": "dhcp",
        "port": 67,
        "protocol": "UDP",
        "targetPort": "dhcp"
      }
    ],
    "selector": {
      "rubykaigi.org/app": "kea4"
    },
    "type": "LoadBalancer"
  }
}
---
