{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "labels": {
         "rubykaigi.org/app": "syslog-fluentd"
      },
      "name": "fluentd"
   },
   "spec": {
      "replicas": 2,
      "selector": {
         "matchLabels": {
            "rubykaigi.org/app": "syslog-fluentd"
         }
      },
      "template": {
         "metadata": {
            "labels": {
               "rubykaigi.org/app": "syslog-fluentd"
            }
         },
         "spec": {
            "containers": [
               {
                  "args": [
                     "--config",
                     "/config/fluent.conf"
                  ],
                  "env": [ ],
                  "image": "005216166247.dkr.ecr.ap-northeast-1.amazonaws.com/fluentd:49feb127d8ab931f9c9ec5809284b9e7df26cc2b",
                  "livenessProbe": {
                     "failureThreshold": 2,
                     "httpGet": {
                        "path": "/api/plugins.json",
                        "port": 10068,
                        "scheme": "HTTP"
                     },
                     "periodSeconds": 3
                  },
                  "name": "fluentd",
                  "ports": [
                     {
                        "containerPort": 5140,
                        "name": "syslog",
                        "protocol": "UDP"
                     },
                     {
                        "containerPort": 24231,
                        "name": "prom"
                     },
                     {
                        "containerPort": 10068,
                        "name": "healthz"
                     },
                     {
                        "containerPort": 24224,
                        "name": "forward"
                     }
                  ],
                  "readinessProbe": {
                     "httpGet": {
                        "path": "/api/plugins.json",
                        "port": 10068,
                        "scheme": "HTTP"
                     }
                  },
                  "resources": {
                     "requests": {
                        "cpu": "5m",
                        "memory": "192M"
                     }
                  },
                  "volumeMounts": [
                     {
                        "mountPath": "/config",
                        "name": "config"
                     }
                  ]
               }
            ],
            "securityContext": {
               "fsGroup": 9999,
               "runAsUser": 9999
            },
            "serviceAccountName": "syslog",
            "volumes": [
               {
                  "configMap": {
                     "name": "fluentd-config"
                  },
                  "name": "config"
               }
            ]
         }
      }
   }
}
