#cloud-config
users:
  - name: rk
    primary_group: rk
    uid: 3333
    groups: adm,sudo,plugdev,netdev,lxd
    ssh_import_id:
      - gh:hanazuki
      - gh:nna774
      - gh:osyoyu
      - gh:sorah
    sudo: ['ALL=(ALL) NOPASSWD: ALL']
    shell: /bin/bash
