apne1c.acme-responder.rubykaigi.net:
  ssh_options:
    user: rk
  properties:
    run_list:
      - hosts/apne1c.acme-responder.rubykaigi.net/default.rb

apne1d.acme-responder.rubykaigi.net:
  ssh_options:
    user: rk
  properties:
    run_list:
      - hosts/apne1d.acme-responder.rubykaigi.net/default.rb

nat-69.tkyk.rubykaigi.net:
  ssh_options:
    host_name: 10.33.22.222
  properties:
    run_list:
      - hosts/nat-69.tkyk.rubykaigi.net/default.rb

nat-61.venue.rubykaigi.net:
  ssh_options:
    host_name: me0.nat-61.venue.rubykaigi.net
  properties:
    run_list:
      - hosts/nat-61.venue.rubykaigi.net/default.rb

nat-62.venue.rubykaigi.net:
  ssh_options:
    host_name: me0.nat-62.venue.rubykaigi.net
  properties:
    run_list:
      - hosts/nat-62.venue.rubykaigi.net/default.rb

wire-01.venue.rubykaigi.net:
  ssh_options:
    host_name: me0.wire-01.venue.rubykaigi.net
  properties:
    run_list:
      - hosts/wire-01.venue.rubykaigi.net/default.rb

wire-02.venue.rubykaigi.net:
  ssh_options:
    host_name: me0.wire-02.venue.rubykaigi.net
  properties:
    run_list:
      - hosts/wire-02.venue.rubykaigi.net/default.rb

wire-03.venue.rubykaigi.net:
  ssh_options:
    #host_name: me0.wire-03.venue.rubykaigi.net
  properties:
    run_list:
      - hosts/wire-03.venue.rubykaigi.net/default.rb

wire-04.venue.rubykaigi.net:
  ssh_options:
    #host_name: me0.wire-03.venue.rubykaigi.net
  properties:
    run_list:
      - hosts/wire-03.venue.rubykaigi.net/default.rb

show-01.venue.rubykaigi.net:
  properties:
    run_list:
      - hosts/show-01.venue.rubykaigi.net/default.rb

wire.rubykaigi.net:
  properties:
    run_list:
      - hosts/wire.rubykaigi.net/default.rb


