nat-69.tkyk.rubykaigi.net:
  ssh_options:
    host_name: 10.33.22.222
  properties:
    run_list:
      - hosts/nat-69.tkyk.rubykaigi.net/default.rb

nat-61.venue.rubykaigi.net:
  ssh_options:
    host_name: me0.nat-61.venue.rubykaigi.net
  properties:
    run_list:
      - hosts/nat-61.venue.rubykaigi.net/default.rb

nat-62.venue.rubykaigi.net:
  ssh_options:
    host_name: me0.nat-62.venue.rubykaigi.net
  properties:
    run_list:
      - hosts/nat-62.venue.rubykaigi.net/default.rb

show-01.venue.rubykaigi.net:
  properties:
    run_list:
      - hosts/show-01.venue.rubykaigi.net/default.rb


