# vim: ft=nftables
<%- downstream = node.dig(:wire, :interfaces, :downstream) -%>
<%- if downstream -%>
define if_downstream = "<%= downstream.fetch(:name) %>"
<%- end -%>

table inet wire {
  chain prerouting {
    type filter hook prerouting priority raw; policy accept;

<%- if downstream -%>
    iifname $if_downstream fib daddr type != local notrack
<%- end -%>
    iifname "wg_*" fib daddr type != local notrack
  }

  chain input {
    type filter hook input priority filter; policy drop;

    iif lo accept
    ct state established,related accept

    ip protocol icmp accept
    ip6 nexthdr icmpv6 accept

    ip saddr { 10.33.0.0/23, 10.33.128.0/18, 10.33.22.0/24 } tcp dport { ssh } accept
    ip saddr { 10.33.128.0/18 } tcp dport { 9100, 9324, 9466 } accept
    ip6 saddr { 2001:df0:8500:ca00::/64, 2001:df0:8500:caa0::/64, 2406:da14:dfe:c000::/56 } tcp dport { ssh } accept

<%- if downstream -%>
    iifname $if_downstream tcp dport bgp accept
<%- end -%>
    iifname "wg_*" tcp dport bgp accept

    counter
  }

  chain forward {
    type filter hook forward priority filter; policy drop;

<%- if downstream -%>
    iifname $if_downstream accept
<%- end -%>
    iifname "wg_*" accept

    counter
  }

  chain output {
    type filter hook output priority filter; policy accept;
  }
}
