#cloud-config
users:
  - name: rk
    primary_group: rk
    uid: 3333
    groups: adm,sudo,plugdev,netdev,lxd
    ssh_import_id:
      - gh:sorah
    sudo: ['ALL=(ALL) NOPASSWD: ALL']
    shell: /bin/bash
bootcmd:
  - [ cloud-init-per, once, ssh-port, bash, '-c', 'echo Port 9922 >> /etc/ssh/sshd_config']
