{
   "jobs": {
      "build": {
         "name": "build",
         "permissions": {
            "contents": "read",
            "id-token": "write"
         },
         "runs-on": "ubuntu-latest",
         "steps": [
            {
               "uses": "actions/checkout@v3"
            },
            {
               "name": "setup docker multiarch",
               "run": "mkdir -p ~/.docker\nsudo docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes --credential yes\n"
            },
            {
               "uses": "docker/setup-buildx-action@v2",
               "with": {
                  "install": true
               }
            },
            {
               "uses": "aws-actions/configure-aws-credentials@v1",
               "with": {
                  "aws-region": "ap-northeast-1",
                  "role-skip-session-tagging": true,
                  "role-to-assume": "arn:aws:iam::005216166247:role/GhaDockerPush"
               }
            },
            {
               "id": "login-ecr",
               "uses": "aws-actions/amazon-ecr-login@v1"
            },
            {
               "uses": "docker/build-push-action@v3",
               "with": {
                  "context": "docker/kea",
                  "platforms": "linux/arm64",
                  "push": true,
                  "tags": "${{ steps.login-ecr.outputs.registry }}/kea:${{ github.sha }},${{ steps.login-ecr.outputs.registry }}/kea:latest"
               }
            }
         ]
      }
   },
   "name": "docker-kea",
   "on": {
      "push": {
         "branches": [
            "master",
            "test"
         ],
         "paths": [
            "docker/kea/**"
         ]
      }
   }
}
